### ISSUE TITLE
Crash when showing helpers list without any registered helpers

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#10]
When Showing the helpers list before I open the Event I receive the following error message: 
```
Internal Server Error: /StuStaCulum2017/helpers/

NoReverseMatch at /StuStaCulum2017/helpers/
Reverse for 'export_date' with arguments '('StuStaCulum2017', 'excel', '')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['(?P<event_url_name>[a-zA-Z0-9]+)/export/(?P<type>[a-z]+)/all/(?P<date_str>\\d{4}-\\d{2}-\\d{2})/$']
```

What I did to temporally circumvent this was to comment out the "export single day" feature in the template - to be more specific:

```
<a href="{#{% url 'export_date' event.url_name 'excel' day_str %}#}" class="icon">
```

**Comment by svenhertle** [comment]
I cannot reproduce this.

It seems that this template code sets `day_str` to '': `{% with day_str=day|date:"Y-m-d" %}`

Could you give me some hints how to reproduce the bug?

**Comment by Sorontik** [comment]
Just faced the Same Bug:

Setting:
Ubuntu 16.04 LTS (Running in VirtualBox VM on WIN 10 Host)
MySQL-Server (5.7.19-0ubuntu0.16.04.1 - (Ubuntu), Protocol version: 10, Server charset: UTF-8)
phpmyadmin on apache-server for manual database exploration

helfertool installed into pyvenv, all dependencies fulfilled (especially requirements.txt and "manage.py bower install"
as well as correct db-connection specification in settings


Now, i can do the following steps to reproduce the error:
create Database and db-user with appropriate rights

run "manage.py migrate"
run "manage.py createsuperuser"

open in browser and log in,
create new event (set url, name and date, keep defaults)
add Job
add Shift

then try to view "Helpers and coordinators" => boom.


This is what i managed to find out:

The Problem is, that 'days' in >registration/templates/registration/admin/helpers.html:39< is not empty, but contains no helpful elements.

traced back to >registration/views/helper.py:46<
the var 'days' is a QuerySet that contains only the Element "None": <QuerySet [None]>

this is caused by the "annotate(day=TruncDate('begin'))" returning "<QuerySet [None]>"

i am not toally sure, why this is the case, but i came across a forum post [0], pointing to the issue that there might be incompatibilities between Django and Mysql regarding the representation of timezones


looking into my db via phpmyadmin, i can approve the following from the forum post:
my registration_shift.begin and .end columns are of type 'datetime(6)' and show no sign of any timzone-information being stored



[0] : https://stackoverflow.com/questions/24548902/datetimefield-queryset-returning-none-in-django

**Comment by svenhertle** [comment]
Thank you for the debugging.

According to the mentioned stackoverflow thread, this issue is caused by the database connector:

> This issue is caused by an outdated version of MySQL-python not by Django or migrations system.
>
> Using mysqlclient (which is an updated fork of MySQL-python) solves this problem.

In my setup with mysqlclient, i have the correct type datetime. Which DB engine are you using?

**Comment by EdererK** [comment]
I'm struggling with nearly the same issue,
the difference: The problem only occurs if helpers are registered.
I'm using the newest mysqlclient with mariadb

NoReverseMatch at /test/helpers/

Reverse for 'export_date' with arguments '('test', 'excel', '')' not found. 1 pattern(s) tried: ['(?P<event_url_name>[a-zA-Z0-9]+)/export/(?P<type>[a-z]+)/all/(?P<date_str>\\d{4}-\\d{2}-\\d{2})/$']

**Comment by svenhertle** [comment]
The reason for this problem is that time zone information is missing in MySQL... You have to load that manually:

mysql_tzinfo_to_sql /usr/share/zoneinfo | sudo mysql -u root mysql
sudo systemctl restart mysql

I've updates the documentation (https://docs.helfertool.org/deploy/installation/preparation.html#mariadb)
