### ISSUE TITLE
New field for Helper-Skills

### ISSUE THREAD

**Issue by Nos-** [helfertool/helfertool#20]
Special skills like able to speak several languages, technical knowledge or a good planning-ability are valuable for teams. Everyone should have the possibility to note down his special skills so others can search for it. Maybe a tag-cloud for all the skills would be handy.

**Comment by svenhertle** [comment]
Thank you! Should be considered for #15

**Comment by Tomatower** [comment]
Is this fixed with #32 ?

Prerequisites enable you to have predefined skills or information events that a helper has to have or has to attend. Such a skill is boolean: either you fulfill it or you dont.

The feature was designed with skills in mind like

* speaks fluently german
* visited the security briefing before the event
