### ISSUE TITLE
Move the Address in registration/privacy

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#3]
In `helfertool/registration/templates/registration/privacy/statement.{html,txt}` contains the address of Fachschaft MPI - is it possible to move this into `helfertool/settings.py`?

**Comment by svenhertle** [comment]
Yes, this is a good suggestion.

The text currently refers to the BayDSG since we are a 	public institution. Probably you have to comply with the BDSG, so you also have to change the text.

Currently I plan to split the configuration in "Django stuff" and real configuration options. When doing this, I try to find a better solution for the texts.

**Comment by Tomatower** [comment]
Until then - how can I change this?
If I just planly change the contents of this file, the translation is not working anymore.

**Comment by svenhertle** [comment]
It should work since the files contain the German and English text:

```
{% if LANGUAGE_CODE == 'de' %}
german text
{% else %}
english text
{% endif %}
```

Since no trans or blocktrans template tags are used, it should not be necessary to change the translation files.

Or do I misunderstand the problem?

**Comment by Tomatower** [comment]
It somehow hat unicode issues (München seems to be a difficult word...) - and it did not read the html files correctly, now it did work!
